//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('PaymentMethods')
export class PaymentMethodsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  methodId: number;

  @Column('integer', { nullable: true })
  userId: number;

  @Column('text', { nullable: true })
  methodType: string;

  @Column('text', { nullable: true })
  details: string;
}
