//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Transactions')
export class TransactionsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  transactionId: number;

  @Column('integer', { nullable: true })
  senderId: number;

  @Column('integer', { nullable: true })
  receiverId: number;

  @Column('real', { nullable: true })
  amount: number;

  @Column('date', { nullable: true })
  transactionDate: Date;

  @Column('text', { nullable: true })
  status: string;

  @Column('text', { nullable: true })
  scannedData: string;

  @Column('date', { nullable: true })
  dateOfScan: Date;

  @Column('text', { nullable: true })
  deviceUsedForScanning: string;
}
